/**
 * Seed ClimaScope's initial users and the Downtown Miami demo area.
 *
 *   bun scripts/seed.ts            # idempotent: creates what's missing
 *   bun scripts/seed.ts --reset    # also rotates passwords for the seed users
 *
 * Generated passwords are written to /home/team/shared/CREDENTIALS.md — NEVER
 * under src/ or any served path.
 */
import { writeFileSync } from "node:fs";
import { db } from "~/lib/db";
import { findUserByEmail, createUser } from "~/lib/auth";
import { CLIMATE_VALUES } from "~/lib/climates";

const CREDENTIALS_PATH = "/home/team/shared/CREDENTIALS.md";
const RESET = process.argv.includes("--reset");

function strongPassword(): string {
  // 20 hex chars from crypto RNG = 80 bits of entropy.
  return Array.from(new Uint8Array(10), (b) => b.toString(16).padStart(2, "0")).join("");
}

type SeedEntry = { email: string; password: string; role: string; name: string; created: boolean };

async function ensureUser(
  email: string,
  name: string,
  role: "admin" | "analyst",
  created: SeedEntry[]
) {
  const existing = findUserByEmail(email);
  if (existing && !RESET) {
    created.push({ email, password: "(unchanged — see previous CREDENTIALS.md)", role: existing.role, name, created: false });
    return existing;
  }
  const password = strongPassword();
  if (existing) {
    // Rotate: replace the hash, keep the user id.
    const { hashPassword } = await import("~/lib/auth");
    db.run("UPDATE users SET password_hash = ? WHERE id = ?", [
      await hashPassword(password),
      existing.id,
    ]);
    created.push({ email, password, role: existing.role, name, created: true });
    return existing;
  }
  const user = await createUser({ email, name, password, role });
  created.push({ email, password, role, name, created: true });
  return user;
}

async function main() {
  const created: SeedEntry[] = [];

  const admin = await ensureUser("admin@climascope.app", "ClimaScope Admin", "admin", created);
  await ensureUser("demo@climascope.app", "Demo Analyst", "analyst", created);

  // Demo area — Downtown Miami.
  const climate = "tropical";
  if (!CLIMATE_VALUES.includes(climate)) throw new Error("bad climate type");
  const demoName = "Downtown Miami Demo";
  const existingArea = db
    .query<{ id: number }, [string]>("SELECT id FROM areas WHERE name = ? AND is_demo = 1")
    .get(demoName);
  if (!existingArea) {
    db.run(
      `INSERT INTO areas (name, city, country, center_lat, center_lng, radius_km, climate_type, is_demo, created_by)
       VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?)`,
      [demoName, "Miami", "US", 25.7743, -80.1937, 3, climate, admin.id]
    );
    console.log(`created demo area “${demoName}”`);
  } else {
    console.log(`demo area “${demoName}” already exists`);
  }

  // Credentials file (outside the site tree, never served).
  const lines: string[] = [];
  lines.push("# ClimaScope credentials");
  lines.push("");
  lines.push(`Generated by \`bun scripts/seed.ts\` on ${new Date().toISOString()}.`);
  lines.push("Keep this file private — it is outside the site tree and never served.");
  lines.push("");
  lines.push("| Account | Email | Password | Role |");
  lines.push("|---|---|---|---|");
  for (const e of created) {
    lines.push(`| ${e.name} | ${e.email} | \`${e.password}\` | ${e.role} |`);
  }
  lines.push("");
  lines.push("- The demo area “Downtown Miami Demo” (25.7743, -80.1937, r=3 km, tropical) is visible to every account.");
  lines.push("- Rotate with `bun scripts/seed.ts --reset` (rewrites this file).");
  lines.push("");
  writeFileSync(CREDENTIALS_PATH, lines.join("\n") + "\n", { mode: 0o640 });
  console.log(`wrote ${CREDENTIALS_PATH}`);

  for (const e of created) {
    console.log(`user ${e.email} (${e.role}): ${e.created ? "created" : "exists"}`);
  }
}

await main();
